config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'rooms/index'
  
  
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'pages#home'

  resources :interests 

  get 'admin/pending_approvals', to: 'admin#pending_approvals'
  get 'admin/confirmed_approvals', to: 'admin#confirmed_approvals'
  get 'admin/create_categories', to: 'admin#create_categories'
  get 'admin/seller', to: 'admin#seller'

  # Defines the route for approving and rejecting products
  get 'admin/approve_product/:id', to: 'admin#approve_product', as: 'approve_product'
  get 'admin/reject_product/:id', to: 'admin#reject_product', as: 'reject_product'

  match 'admin/approve_product/:id', to: 'admin#approve_product', via: %i[get patch]
  match 'admin/reject_product/:id', to: 'admin#reject_product', via: %i[get patch]

  patch 'admin/approve_product/:id', to: 'admin#approve_product'
  patch 'admin/reject_product/:id', to: 'admin#reject_product'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  delete '/products/:id', to: 'products#destroy', as: 'delete_product'

  get 'user/:id', to: 'users#show', as: 'user'

  resources :rooms do
    resources :messages
  end

  resources :categories

  get 'pages/map', to: 'pages#map'
  

  get '/products/:id/smail', to:'products#smail', as: 'smail_product'

  get '/products/:id/sell', to:'products#sell', as: 'sell_product'

  get 'messages', to: 'static_pages#messages'
  get 'messages/open', to: 'messages#create'

  get '/account/', to: 'pages#account', as: 'show_current_account'
  get '/payments/success', to: 'payments#success', as: 'success_payment'
  get '/payments/failure', to: 'payments#failure', as: 'failure_payment'
  post '/payments/webhook', to: 'payments#webhook'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    has_many :products
end

app/models/condition.rb
class Condition < ApplicationRecord
    has_many :products
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { broadcast_append_to room }
  before_create :confirm_participant

  def confirm_participant
    return unless room.is_private

    is_participant = Participant.where(user_id: user.id, room_id: room.id).first
    throw :abort unless is_participant
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :user
    belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    validates :category_id, presence: true
    belongs_to :user, optional: true
    belongs_to :condition
    belongs_to :category
    has_one_attached :picture
    

   
    scope :search, ->(search) { where('name like ?', "%#{search}%") }
    scope :search, ->(search) {joins(:category).where("categories.name like ?", "%#{search}%").distinct}
    scope :condition_id, ->(condition_id) { where condition_id: condition_id }
    scope :category_id, ->(category_id) { where category_id: category_id }
end

app/models/room.rb
class Room < ApplicationRecord

    validates_uniqueness_of :name 
    scope :public_rooms, -> { where(is_private: false)}
    after_create_commit { broadcast_if_public }
    has_many :messages
    has_many :participants, dependent: :destroy 

    def broadcast_if_public 
        broadcast_append_to "rooms" unless self.is_private
    end 

    def self.create_private_room(users, room_name)
        single_room = Room.create(name: room_name, is_private: true)
        users.each do |user|
          Participant.create(user_id: user.id, room_id: single_room.id)
        end
        single_room
    end
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable, 
  :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :products, dependent: :destroy
  has_many :payments

  scope :all_except, ->(user) { where.not(id: user) }
  after_create_commit { broadcast_append_to "users" }
  has_many :messages

  def self.from_omniauth(auth)
    where(provider: auth.provider, user_id: auth.user_id).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name 
      user.avatar_url = auth.info.image
    end
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

    def pending_approvals 
        @products = Product.where(is_approved: false).order('created_at DESC')
    end

    def confirmed_approvals 
        @products = Product.where(is_approved: true).order('created_at DESC')
    end

    def seller
        @products =  Product.all
        @users = User.all
    end 

    def create_categories
        @categories = Category.all
    end

    def edit 
        @product = Product.find(params[:id])
    end

    def update 
        @product = Product.find(params[:id])
        @product.update(product_params)
        redirect_to admin_path, notice: 'Product is successfully updated.'
    end

    def approve_product
        @product = Product.find(params[:id])
        if @product.update_attribute(:is_approved, true)
            
            redirect_to @product, notice: 'Product approved.'
        end
    end

    def reject_product
        @product = Product.find(params[:id])
        if @product.update_attribute(:is_approved, false)
            @product.destroy 
            #redirect_to admin_pending_approvals_path, notice: 'Product rejected.'
            #flash.now[:success] = "Product rejected."
            redirect_to request.referrer, notice: 'Product rejected.'
        end
    end 

    private 

    def product_params
        params.require(:product).permit(:is_approved) 
    end 

end

app/helpers/admin_helper.rb
module AdminHelper
    def require_admin
      unless current_user.is_admin?
        flash[:danger] = 'You must be an admin to perform this action'
        redirect_to root_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/confirmed_approvals.html.erb
<% if user_signed_in? && current_user.admin? %>
    <div class="row">
            <div class="col-md-12 my-5 border rounded shadow">
            <h3 class="my-4 text-center">Confirmed Products</h3>
            <table class="table table-striped">
                <thead>
                <tr>    
                    <th>Name</th>
                    <th>Location</th>
                    <th>Price</th>
                    <th>Seller</th> 
                </tr>
                </thead>

                <tbody>
                <% @products.each do |product| %>
                    <tr>
                    <td><%= product.name %></td>
                    <td><%= product.location %></td>
                    <td><%= product.price %></td>
                    <td><%= product.user.name %></td>               
                    </tr>
                <% end %>
                </tbody>
            </table>       
            </div>       
    </div>
<% else %>
  <h3>Sign in with an admin account</h3>


<% end %>

app/views/admin/create_categories.html.erb
<h3>Categories</h3>

<%= link_to "Add category", new_category_path %>

<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.name, edit_category_path(category) %></li>
  <% end %>
</ul>

app/views/admin/pending_approvals.html.erb
<% if user_signed_in? && current_user.admin? %>
  <div >
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
  </div>


  <% if @products.count == 0 %>
  <div class="container border shadow rounded my-5">
      <h3 class="my-4 text-center">No new products pending for approval </h3>
  </div>
    
  <% else %>
  <div class="border shadow rounded my-5">
      <div class="row">
          <div class="col-md-12">
          <h3 class="my-4 text-center">Pending Products</h3>
          <table class="table table-striped">
              <thead>
              <tr>
                  <th>Name</th>
                  <th>Location</th>
                  <th>Price</th>
                  <th>Seller</th> 
                  
              </tr>
              </thead>
              <tbody>
              <% @products.each do |product| %>
                  <tr>
                  <td><%= product.name %></td>
                  <td><%= product.location %></td>
                  <td><%= product.price %></td>
                  <td><%= product.user.name %></td>
                  
                  <td>
                  <%= link_to "Accept", approve_product_path(product.id), class:"btn btn-success" %>
                  <%= link_to "Reject", reject_product_path(product.id), class:"btn btn-danger" %>
                  </td> 
                  </tr>
              <% end %>
              </tbody>
          </table>
          </div>
      </div>
      
  </div>
  <% end %>
  <% else %>
  <h3>Sign in with an admin account</h3>


<% end %>

app/views/admin/seller.html.erb
<% if user_signed_in? && current_user.admin? %>

    <div class="col-md-12 my-5 border rounded shadow">
        <h3 class="my-4 text-center">Sellers' Products</h3>
    </div>

    <% @users.each do |i| %>    
            <% k = Product.where(:user_id => i.id) %>
            <% if k.count != 0 %>
                <h4>Seller Name - <%= i.name %></h4>
                
                <% k.each do |j| %>
                <div class=" listing-box">
                    <div class="thumbnail account-card">
                        <%= image_tag((j.picture if j.picture.attached?), class: "account-img")%>
                        <div class="caption">
                            <h3><%= j.name %></h3>
                            <h5>Price: <%= number_to_currency(j.price / 100) %></h5>
                            <h5>Condition: <% j.condition.name %></h5>
                            <div class="account-button-container">
                                <%= link_to("View", product_path(j), class: "btn btn-default") %>
                            </div>
                        </div>
                    </div>
                </div>

                <% end %><br />
            <% end %>
    <% end %>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
    <div class="col-md-12">
        <p>Built with Ruby on Rails, styled with Bootstrap.</p>
    </div>
</div>

app/views/shared/_topnav.html.erb
<nav class="navbar navbar-light">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to("Instruments Market", root_path, class: "navbar-brand") %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <% if user_signed_in? && !current_user.admin? %>
              <li><%= link_to("Sign Out", destroy_user_session_path, method: :delete) %></li>
              <li><%= link_to("New Listing", new_product_path) %></li>


            <% elsif user_signed_in? && current_user.admin? %>
              <li><%= link_to("Sign Out", destroy_user_session_path, method: :delete) %></li>
              <li><%= link_to("New Listing", new_product_path) %></li>
              <li><%= link_to("Pending Approval", admin_pending_approvals_path, class: "nav-item nav-link") %></li> 
              <li><%= link_to("Confirmed Approval", admin_confirmed_approvals_path, class: "nav-item nav-link") %></li>
              <li><%= link_to("Create Categories", admin_create_categories_path, class: "nav-item nav-link") %></li>
              <li><%= link_to("Seller", admin_seller_path, class: "nav-item nav-link") %></li>



            <% else %>
              <li><%= link_to("Sign Up", new_user_registration_path, class: "nav-item nav-link") %></li>
              <li><%= link_to("Log In", new_user_session_path, class: "nav-item nav-link") %></li>
            <% end %>
          </ul>

          <form class="navbar-form navbar-left" action="<%= products_path %>" method="GET">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search..." name="search">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
          </form>

          


          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to("My Account", show_current_account_path) %>
            <% end %>
          </ul>

          
        </div>
</nav>