config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'rooms/index'
  
  
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'pages#home'

  resources :interests 

  get 'admin/pending_approvals', to: 'admin#pending_approvals'
  get 'admin/confirmed_approvals', to: 'admin#confirmed_approvals'
  get 'admin/create_categories', to: 'admin#create_categories'
  get 'admin/seller', to: 'admin#seller'

  # Defines the route for approving and rejecting products
  get 'admin/approve_product/:id', to: 'admin#approve_product', as: 'approve_product'
  get 'admin/reject_product/:id', to: 'admin#reject_product', as: 'reject_product'

  match 'admin/approve_product/:id', to: 'admin#approve_product', via: %i[get patch]
  match 'admin/reject_product/:id', to: 'admin#reject_product', via: %i[get patch]

  patch 'admin/approve_product/:id', to: 'admin#approve_product'
  patch 'admin/reject_product/:id', to: 'admin#reject_product'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  delete '/products/:id', to: 'products#destroy', as: 'delete_product'

  get 'user/:id', to: 'users#show', as: 'user'

  resources :rooms do
    resources :messages
  end

  resources :categories

  get 'pages/map', to: 'pages#map'
  

  get '/products/:id/smail', to:'products#smail', as: 'smail_product'

  get '/products/:id/sell', to:'products#sell', as: 'sell_product'

  get 'messages', to: 'static_pages#messages'
  get 'messages/open', to: 'messages#create'

  get '/account/', to: 'pages#account', as: 'show_current_account'
  get '/payments/success', to: 'payments#success', as: 'success_payment'
  get '/payments/failure', to: 'payments#failure', as: 'failure_payment'
  post '/payments/webhook', to: 'payments#webhook'
end

app/models/product.rb
class Product < ApplicationRecord
    validates :category_id, presence: true
    belongs_to :user, optional: true
    belongs_to :condition
    belongs_to :category
    has_one_attached :picture
    

   
    scope :search, ->(search) { where('name like ?', "%#{search}%") }
    scope :search, ->(search) {joins(:category).where("categories.name like ?", "%#{search}%").distinct}
    scope :condition_id, ->(condition_id) { where condition_id: condition_id }
    scope :category_id, ->(category_id) { where category_id: category_id }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user!, except: %i[index show]
    before_action :set_product, only: [:show]
    before_action :set_user_product, only: %i[edit update destroy]
    before_action :set_categories
 
    def index

      @products = Product.order('created_at desc').where('purchased = false').page params[:page]

      @products = @products.search(params[:search]) if params[:search].present?
      
      if params[:condition_id].present?
        @products = @products.condition_id(params[:condition_id])
      end
      if params[:category_id].present?
        @products = @products.category_id(params[:category_id])
      end
    end

    def sell 
      @product = Product.find(params[:id])
      @seller = @product.user_id
    end

    def smail 
      @product = Product.find(params[:id])
      @seller = @product.user_id
      @current_user = current_user
      InterestMailer.with(seller_id: @seller, current_user: @current_user).notify.deliver_now
      redirect_to request.referrer, notice: 'Interest mail sent to the seller!!'
    end
  
    def show
      @user = @product.user   
      if user_signed_in? && current_user != @product.user
        response = auspost_api_get
        @full_cost = @product.price + (@delivery_cost.to_f * 100)
        @session_id = session.id
      end
    end
  
    def new
      @product = Product.new
      @categories = Category.all
      @conditions = Condition.all
    end
  
    def edit
      @categories = Category.all
      @conditions = Condition.all
      @product = Product.find(params[:id])
    end
  
    def create
      @product = current_user.products.create(product_params)
      @product.location = current_user.postcode
      @product.purchased = false
  
      if @product.save
        redirect_to @product, notice: 'Product was successfully created, and waiting for approval.'
      else
        render :new
      end
    end
  
    def update
      if @product.update(product_params)
        redirect_to @product, notice: 'Product was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @product = set_product
      @product.destroy if @product.present?
  
      redirect_to products_url, notice: 'Product was successfully destroyed.'
    end
  
    
    private

    def set_product
      @product = Product.find(params[:id])
    end
  
   
    def product_params
      params.require(:product).permit(:name, :price, :location, :description, :category_id, :condition_id, :picture)
    end
  
    
    def set_user_product
      @product = current_user.products.find_by_id(params[:id])
  
      redirect_to products_path if @product.nil?
    end

    def set_categories
      @categories = Category.all.order(:name)
    end 
  
   
    def auspost_api_get
      seller_postcode = @product.location
      buyer_postcode = current_user.postcode
  
      
      length = rand(5..25)
      width = rand(5..25)
      height = rand(5..25)
      weight = rand(1..10)
      
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.erb
<%= simple_form_for @product do |f| %>

	<% if product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being created:</h2>

        <ul>
          <% product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

	<%= f.input :name, label: "Item Name", required: true %>

	<%= f.input :price, label: "Price in cents", required: true %>

	<%= f.input :description, required: true %>


	<%#= f.input :category_id, as: :select, collection: @categories, prompt: 'Select Category', label: false, required: true %>

	<%= f.input :condition_id, as: :select, collection: @conditions, prompt: 'Select Condition', label: false, required: true %>

  <div>
    <%= f.label :category, style: "display: block" %>
    <%= f.select :category_id, options_for_select(@categories.collect { |cat| [cat.name, cat.id]}) %>
  </div>

  <%= f.input :picture, as: "file", accept: "image/png,image/gif,image/jpeg,image/jpg", label: "Image of Item", required: true %>

  <div class="map-container">
    <div id="map"></div>
  </div>

  <%= f.button :submit, class: "btn btn-default" %>
  
<% end %>

app/views/products/_index_display.html.erb
<% @products.each do |product| %>
    <% if product.is_approved == true %>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <%= image_tag product.picture if product.picture.attached? %>
                <div class="caption">
                    <h3><%= product.name %></h3>
                    <h3><%= product.is_approved %></h3>
                    <div class="condition-container">
                        <%= link_to("View Product", product_path(product), class: "btn btn-default") %>
                        <%= product.condition.name %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
<% end %>

app/views/products/edit.html.erb
<%= render("shared/topnav") %>
<div class="container">
    <h1>Editing Product</h1>

    <%= render 'form', product: @product %>
</div>

app/views/products/index.html.erb
<%= render("shared/topnav") %>

<div class="container">

  <p id="notice"><%= notice %></p>
  
  <div class="row index-row">
    <h3><%#= @products.count %> Results found</h3>
    <div>
      <%= form_with url: products_path, method: "get", local: true, :html => {class: "filter-form"} do |form| %>
        
        <div class="field">
          <%= form.label :category_id %><br>
          <%= form.collection_select :category_id, Category.order(:name), :id, :name, include_blank: true %>
        </div>

        <div class="field">
          <%= form.label :condition_id %><br>
          <%= form.collection_select :condition_id, Condition.order(:name), :id, :name, include_blank: true %>
        </div>

        <%= form.submit "Filter Listings", class: "btn btn-default btn-xs field" %>

      <% end %>
    </div>
  </div>

  <div class="row">
    <% @products.each do |product| %>
    <% if product.is_approved == true %>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <%= image_tag product.picture if product.picture.attached? %>
          <div class="caption">
            <h3><%= product.name %></h3>
            <h5>Status = Approved</h5>

            <div class="condition-container">
                <%= link_to("View Product", product_path(product), class: "btn btn-default") %>
                <%= p Condition.find(product.condition_id).name + " condition" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <% end %>
  </div>

  
  <div>
    <%= paginate @products %>
  </div>

</div>

<%= render("shared/footer") %>

app/views/products/new.html.erb
<%= render("shared/topnav") %>
<div class="container">
    <div class="col-md-8 col-md-offset-2 form-bg">
        <h1>New Product</h1>
        <p><b>*</b> Indicates required field</p>

        <%= render 'form', product: @product %>
    </div>
</div>

app/views/products/show.html.erb
<%= render("shared/topnav") %>

<div class="container">
  <div class=".col-xs-12 .col-md-8">
    <div class="product-show">
        <p id="notice"><%= notice %></p>
        <div class="product-box">
          <div class="product-details">

            <h2><%= @product.name %></h2>
            <p class="product-posted-by">Listed by <%= @product.user.name %> | <%= time_ago_in_words(@product.created_at) %> ago.</p>
            <p>Location: <%= @product.location %></p>
            <p>Condition: <%= @product.condition.name %></p>
            <p>Category: <%= @product.category.name %></p>
            <p>Description: <%= @product.description %></p>
            <h3>Price: <%= number_to_currency(@product.price / 100.0) %></h3>


            <% if user_signed_in? && current_user != @product.user %>
              <h5>Shipping: <%= number_to_currency(@delivery_cost) %></h5>
              <h5><%= @delivery_time %></h5>
            <% end %>
            <p class="product-posted-by">All currencies are $AUD</p>


            <% if user_signed_in? %>
              <% if @product.user_id == current_user.id %>
                <%= link_to("Edit", edit_product_path(@product), class: "btn btn-default") %>
                <%= link_to("Delete", product_path(@product), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default") %>
              <% else %>

                <button data-stripe="payment" class="btn btn-default">Buy Now</button>
                <button class="btn btn-default"><%= link_to "Interest", smail_product_path %></button>
                <button class="btn btn-block btn-info text-uppercase mb-4" id="show-tel" ><i class="fas fa-phone mr-2"></i><%= @user.telephone %></button>
                <button class="btn btn-default"><%= link_to "Start Chatting", rooms_path %></button>


                <script src="https://js.stripe.com/v3/"></script>

                <script>
                  document
                  .querySelector("[data-stripe='payment']")
                  .addEventListener("click", () => {
                    const stripe = Stripe(
                    "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
                    );

                    stripe.redirectToCheckout({
                    sessionId: "<%= @session_id %>"
                    });
                  });
                </script>
              <% end %>
            <% end %>
          </div>
    
          <div class="product-image-box">
            <% if @product.picture.attached? %>
              <%= image_tag((@product.picture), class: "image-box")%>
            <% end %>
          </div>
        </div>
    </div>
  </div>
      
</div>

<button class="btn btn-default"><%= link_to "Back", 'javascript:history.back()', class: "btn btn-outline-secondary" %></button>

<%= render("shared/footer") %>